config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :products, only: [:create, :destroy]
  end

  root 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @product = Product.new
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product.category, notice: 'El producto ha sido creado.' }
      else
        format.html { render :new}
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to @product.category, notice: 'El producto fue eliminado' 
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<div class="row justify-content-center">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>Nombre</th>
          <th> Cantidad</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= link_to category.name, category %></td>
            <td><%= category.products.count %></td>
            <td>
              <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-outline-info'%>
              <%= link_to 'Destroy', category, class: 'btn btn-outline-danger', 
              method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="row justify-content-center">
  <div class="col-xs-12 col-sm-12 col-md-6">
    <h3> Categoría : <%= @category.name %></h3>

    <%= form_with(model: [@category, @product]) do |form| %>
      <%= form.hidden_field :category_id, value: @category.id %>

      <div class="form-group">
        <%= form.label :name, 'Nombre' %>
        <%= form.text_field :name, id: :product_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :price, 'Precio' %>
        <%= form.number_field :price, id: :product_price, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit 'Ingresar', class: 'btn btn-primary'%>
      </div>
    <% end %>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <table class="table mt-3">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @category.products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td>$<%= product.price %></td>
          <td>
            <%= link_to 'Eliminar', category_product_path(@category, product),
            class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item">
        <a class="btn btn-outline-info mx-1 my-1" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="btn btn-outline-success mx-1 my-1" href="<%= new_category_path %>">Nueva categoría</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Actividad27</title>
    <%= csrf_meta_tags %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <div class="container"> 
      <%= yield %>
    </div>
  </body>
</html>